### PR TITLE
Adding question 6

### PR DESCRIPTION
**Pull request by aazar412**

### CODE REVIEW

**Review by meato76 — CHANGES_REQUESTED** [review]
it's not finished !

**Review by aazar412 — COMMENTED** [review]
I ADDED THE CHANGES

**Review by Eshwa12 — APPROVED** [review]

**Comment by Eshwa12** [comment]
i just approved

**Review by Vikito93 — APPROVED** [review]

**Review by meato76 — APPROVED** [review]
looks good now

**Pull request merged**
